/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multikeyword_search;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Base64;
import java.util.Calendar;
import java.util.Date;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.Cipher;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;
import javax.swing.JOptionPane;
import static multikeyword_search.Login.userName2;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author CMP
 */
public class Data_User extends javax.swing.JFrame {

    /**
     * Creates new form Data_User
     */
    public Data_User() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kkk = new javax.swing.JTextField();
        k = new javax.swing.JTextField();
        kk = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        skey = new javax.swing.JTextField();
        name2 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Secure Searches: A Fast & Accurate Privacy Preserving");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Retrieval System For Cloud Data");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, -1, -1));

        kkk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        kkk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kkkActionPerformed(evt);
            }
        });
        jPanel3.add(kkk, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 120, 30));

        k.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kActionPerformed(evt);
            }
        });
        jPanel3.add(k, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 120, 30));

        kk.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        kk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kkActionPerformed(evt);
            }
        });
        jPanel3.add(kk, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 120, 30));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Enter Keywords ");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton3.setText("Get Key");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 90, 30));

        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton4.setText("Send Request ");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 170, -1, -1));

        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton6.setText(" File List");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, -1, -1));

        jTable4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Username", "Cloud_ID", "Request_File"
            }
        ));
        jTable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable4MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable4);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 340, 170));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Filename");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 70, -1));

        skey.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel3.add(skey, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 370, 190, 30));

        name2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jPanel3.add(name2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 190, 30));

        jButton8.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton8.setText("Decrypt ");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 420, 110, -1));

        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jButton7.setText("Logout");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 110, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/blue.png"))); // NOI18N
        jLabel7.setText("jLabel3");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 530));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void kkkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kkkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kkkActionPerformed

    private void kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kActionPerformed

    private void kkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kkActionPerformed
     String keyy = null;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         
    
         try {
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dual_cloud", "root", "")) {

                String sql = "SELECT *  FROM cloud_files WHERE id=?";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.setString(1,fid );
                ResultSet rs = pstmt.executeQuery();

             while(rs.next()){
                 keyy=rs.getString(5);
             }
skey.setText(keyy);
            } catch (SQLException ex) {
                Logger.getLogger(CSP1.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (ClassNotFoundException e) {
            System.out.println(e);
        }
        JOptionPane.showMessageDialog(this, "Key is received!");
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        String k1 = k.getText();
        String k2 = kk.getText();

        String k3 = kkk.getText();
        String uname = Login.userName2;
        String uid = Login.uid2;
        try {
            // TODO add your handling code here:
            System.out.println("Connection Start");
            Class.forName("com.mysql.jdbc.Driver");
            System.out.println("Driver Start");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dual_cloud", "root", "");
            System.out.println("Getconnection Start");
            Statement stmt = (Statement) con.createStatement();
            Statement stmt1 = (Statement) con.createStatement();

            String sql = "INSERT INTO download (uid,username,fid,filename,k1,k2,k3,status,d_status) values ('" + Login.uid2 + "','" + Login.userName2 + "','" + "no" + "','" + "no" + "','" + k1 + "','" + k2 + "','" + k3 + "','" + "In progress" + "','" + "In progress" + "')";
            System.out.println(sql);
            stmt.executeUpdate(sql);
JOptionPane.showMessageDialog(this, "Download request is successfully sended!");
        } catch (Exception ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.jdbc.Driver");
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dual_cloud", "root", "")) {

                String sql = "SELECT id,fid,filename,rid,time FROM file_id WHERE uid=? & d_status='Not Downloaded' ";
                PreparedStatement pstmt = con.prepareStatement(sql);
                pstmt.setString(1, Login.uid2);
                ResultSet rs = pstmt.executeQuery();
                while(rs.next()){
                    String i=rs.getString(1);
                    String a = rs.getString(5);
       System.out.println(i);System.out.println(a);
//       DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSS");
//        LocalDateTime dateTime = LocalDateTime.parse(a, formatter);
//        LocalDateTime currentDateTime = LocalDateTime.now();
//        System.out.println(currentDateTime);
//        System.out.println(dateTime);
//        if (dateTime.isBefore(currentDateTime) || dateTime.isEqual(currentDateTime)) {
//            System.out.println("Yes");
 Calendar cal = Calendar.getInstance();
        cal.setTimeZone(TimeZone.getTimeZone("UTC")); // Set time zone to UTC
        java.sql.Timestamp currentTimestamp = new java.sql.Timestamp(cal.getTime().getTime());


        cal.add(Calendar.MINUTE, 10);
        java.sql.Timestamp tenMinutesLater = new java.sql.Timestamp(cal.getTime().getTime());

        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        sdf.setTimeZone(TimeZone.getTimeZone("UTC")); 
                     Date tenMinutesLaterDate = sdf.parse(a);

        
        Date currentTime = new Date();
        
     
        System.out.println("Parsed ten minutes later date: " + sdf.format(tenMinutesLaterDate));
        System.out.println("Current time: " + sdf.format(currentTime));
 if (tenMinutesLaterDate.compareTo(currentTime) >0) {
            System.out.println("No");System.out.println(i);
              String sql2 = "SELECT id,fid,filename,rid FROM file_id WHERE id=?  ";
                PreparedStatement pstmt2 = con.prepareStatement(sql2);
                pstmt2.setString(1, i);
                ResultSet rs2 = pstmt2.executeQuery();
             
 jTable4.setModel(DbUtils.resultSetToTableModel(rs2));
                
 }
 }
            } catch (Exception ex) { System.out.println(ex);
              }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed
    String fid, filename,rid, id;
    private void jTable4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable4MouseClicked
        // TODO add your handling code here:
        int row = jTable4.getSelectedRow();
        fid = (jTable4.getModel().getValueAt(row, 1).toString());

        filename = (jTable4.getModel().getValueAt(row, 2).toString());
        id = (jTable4.getModel().getValueAt(row, 0).toString());
rid = (jTable4.getModel().getValueAt(row, 3).toString());

        name2.setText(filename);

    }//GEN-LAST:event_jTable4MouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
           
            byte[] decodedKey = Base64.getDecoder().decode(keyy);
            SecretKey secretKey = new SecretKeySpec(decodedKey, 0, decodedKey.length, "AES");
            
            
            byte[] encryptedFileContent = Files.readAllBytes(Paths.get("./Files/Public Cloud/"  + name2.getText()));
            
            
            Cipher cipher = Cipher.getInstance("AES");
            cipher.init(Cipher.DECRYPT_MODE, secretKey);
            
            
            byte[] decryptedFileContent = cipher.doFinal(encryptedFileContent);
            
            
            String decryptedFilePath = "./Files/Downloads/" + name2.getText() ;
            
           
            Files.write(Paths.get(decryptedFilePath), decryptedFileContent);
        } catch (Exception ex) {
            
        }
           try {
           

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dual_cloud", "root", "");
            java.sql.Statement stmt = con.createStatement();
            ResultSet rs;

            String sql = "UPDATE file_id SET d_status = 'Downloaded' WHERE id = '" + id + "'";
            stmt.executeUpdate(sql);

        } catch (SQLException ex) {
            
            System.out.println(ex);
        }
           try {
          

            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/dual_cloud", "root", "");
            java.sql.Statement stmt = con.createStatement();
            ResultSet rs;

            String sql = "UPDATE download SET status = 'Downloaded' WHERE id = '" + rid + "'";
            stmt.executeUpdate(sql);

        } catch (SQLException ex) {
        }
        JOptionPane.showMessageDialog(this,"Decrypted and Downloaded");
        new Data_User().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Data_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Data_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Data_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Data_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Data_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField k;
    private javax.swing.JTextField kk;
    private javax.swing.JTextField kkk;
    private javax.swing.JTextField name2;
    private javax.swing.JTextField skey;
    // End of variables declaration//GEN-END:variables
}
